# Regenerates migrations/0014_dz_areas.sql. Usage (from packages/db): python3 scripts/generate-dz-areas.py path/to/algeria_cities.json
import sys, json, re, unicodedata, collections
d = json.load(open(sys.argv[1]))  # algeria_cities.json from github.com/othmanus/algeria-cities
def slug(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode().lower()
    return re.sub(r'[^a-z0-9]+', '-', s).strip('-')
def q(s): return s.replace("'", "''")
def names(ar, fr): return q(json.dumps({'ar': ar.strip(), 'fr': fr.strip()}, ensure_ascii=False))
wil, dai, com = {}, {}, {}
for x in sorted(d, key=lambda x: (x['wilaya_code'], x['daira_name_ascii'], x['commune_name_ascii'])):
    w = 'DZ-' + x['wilaya_code']
    wil[w] = (x['wilaya_code'], x['wilaya_name'], x['wilaya_name_ascii'])
    di = f"{w}-D-{slug(x['daira_name_ascii'])}"
    if di in dai: assert dai[di][1:] == (x['daira_name'], x['daira_name_ascii']), di
    dai[di] = (w, x['daira_name'], x['daira_name_ascii'])
    ci = f"{w}-C-{slug(x['commune_name_ascii'])}"
    assert ci not in com, ci
    com[ci] = (di, x['commune_name'], x['commune_name_ascii'])
print(len(wil), len(dai), len(com))
out = ['-- Algeria: 58 Wilayas, their Daïras and 1541 Communes (Ministry of the Interior list, as published in',
       '-- github.com/othmanus/algeria-cities). Ids are stable; names can be corrected by a later migration.',
       '-- Generated by packages/db/scripts/generate-dz-areas.py.',
       'INSERT INTO geo_areas (id, country, level, parent_id, code, names) VALUES']
rows = [f"('{k}', 'DZ', 'region', NULL, '{v[0]}', '{names(v[1], v[2])}')" for k, v in wil.items()]
out.append(',\n'.join(rows) + '\nON CONFLICT (id) DO NOTHING;\n--> statement-breakpoint')
out.append('INSERT INTO geo_areas (id, country, level, parent_id, code, names) VALUES')
rows = [f"('{k}', 'DZ', 'district', '{v[0]}', NULL, '{names(v[1], v[2])}')" for k, v in dai.items()]
out.append(',\n'.join(rows) + '\nON CONFLICT (id) DO NOTHING;\n--> statement-breakpoint')
out.append('INSERT INTO geo_areas (id, country, level, parent_id, code, names) VALUES')
rows = [f"('{k}', 'DZ', 'locality', '{v[0]}', NULL, '{names(v[1], v[2])}')" for k, v in com.items()]
out.append(',\n'.join(rows) + '\nON CONFLICT (id) DO NOTHING;\n')
open('migrations/0014_dz_areas.sql', 'w').write('\n'.join(out))
